import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { router, useLocalSearchParams } from "expo-router";
import { useMemo, useState } from "react";
import { Modal, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import type { Exercise } from "@fitness-me/shared/api";
import { Button, Card, Field, Screen, Title } from "@/components/ui";
import { colors } from "@/constants/fitme-theme";
import { fitnessApi } from "@/lib/fitness-api";

export default function WorkoutLogger() {
  const { id } = useLocalSearchParams<{ id: string }>(); const qc = useQueryClient(); const workout = useQuery({ queryKey: ["workout", id], queryFn: () => fitnessApi.workout(id!) }); const exercises = useQuery({ queryKey: ["exercises", "logger"], queryFn: () => fitnessApi.exercises() }); const [exercise, setExercise] = useState<Exercise | null>(null); const [picker, setPicker] = useState(false); const [reps, setReps] = useState(""); const [weight, setWeight] = useState(""); const nextSet = useMemo(() => (workout.data?.sets.filter((x) => x.exercise.id === exercise?.id).length ?? 0) + 1, [workout.data, exercise]);
  const log = useMutation({ mutationFn: () => fitnessApi.logSets(id!, [{ exerciseId: exercise!.id, setNumber: nextSet, reps: Number(reps) || undefined, weight: Number(weight) || undefined }]), onSuccess: () => { setReps(""); qc.invalidateQueries({ queryKey: ["workout", id] }); qc.invalidateQueries({ queryKey: ["workouts"] }); } });
  const finish = useMutation({ mutationFn: () => fitnessApi.finishWorkout(id!), onSuccess: () => { qc.invalidateQueries({ queryKey: ["workouts"] }); qc.invalidateQueries({ queryKey: ["dashboard"] }); router.replace("/(tabs)/workouts"); } });
  const w = workout.data;
  return <Screen><ScrollView contentContainerStyle={{ gap: 13, paddingBottom: 28 }} keyboardShouldPersistTaps="handled"><Title sub={w ? `Started ${new Date(w.startedAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}` : "Loading…"}>Workout</Title><Card><Pressable style={s.picker} onPress={() => setPicker(true)}><Text style={exercise ? s.name : s.placeholder}>{exercise?.name ?? "Choose exercise"}</Text><Text style={s.chevron}>⌄</Text></Pressable><View style={s.row}><View style={{ flex: 1 }}><Field label="Reps" value={reps} onChangeText={setReps} keyboardType="number-pad"/></View><View style={{ flex: 1 }}><Field label="Weight (kg)" value={weight} onChangeText={setWeight} keyboardType="decimal-pad"/></View></View><Button title={`Log set ${nextSet}`} busy={log.isPending} disabled={!exercise || (!reps && !weight)} onPress={() => log.mutate()}/>{log.error ? <Text style={s.error}>{log.error.message}</Text> : null}</Card><Text style={s.section}>Logged sets</Text>{w?.sets.map((set) => <Card key={set.id}><View style={s.row}><View style={{ flex: 1 }}><Text style={s.name}>{set.exercise.name}</Text><Text style={s.meta}>Set {set.setNumber}</Text></View><Text style={s.result}>{set.weight ?? "—"} kg × {set.reps ?? "—"}</Text></View></Card>)}<Button title="Finish workout" variant="ghost" busy={finish.isPending} disabled={!w?.sets.length} onPress={() => finish.mutate()}/></ScrollView><Modal visible={picker} animationType="slide" presentationStyle="pageSheet" onRequestClose={() => setPicker(false)}><View style={s.modal}><Text style={s.modalTitle}>Choose exercise</Text><ScrollView contentContainerStyle={{ gap: 8 }}>{exercises.data?.items.map((item) => <Pressable key={item.id} style={s.exercise} onPress={() => { setExercise(item); setPicker(false); }}><Text style={s.name}>{item.name}</Text><Text style={s.meta}>{item.category}</Text></Pressable>)}</ScrollView><Button title="Cancel" variant="ghost" onPress={() => setPicker(false)}/></View></Modal></Screen>;
}
const s = StyleSheet.create({ picker: { minHeight: 52, borderRadius: 12, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.input, paddingHorizontal: 14, flexDirection: "row", alignItems: "center" }, placeholder: { color: colors.muted, flex: 1 }, name: { color: colors.text, fontSize: 15, fontWeight: "800", flex: 1 }, chevron: { color: colors.accent, fontSize: 22 }, row: { flexDirection: "row", alignItems: "center", gap: 10 }, error: { color: colors.danger }, section: { color: colors.text, fontWeight: "900", textTransform: "uppercase", marginTop: 7 }, meta: { color: colors.sub, fontSize: 11 }, result: { color: colors.accent, fontWeight: "900" }, modal: { flex: 1, backgroundColor: colors.bg, padding: 20, gap: 16 }, modalTitle: { color: colors.text, fontSize: 28, fontWeight: "900", textTransform: "uppercase" }, exercise: { backgroundColor: colors.card, borderColor: colors.border, borderWidth: 1, borderRadius: 12, padding: 14 } });
